# Generated by Django 5.1.1 on 2025-01-14 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0003_customuser_cod_customuser_email_confirmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('subiect', models.CharField(max_length=255)),
                ('mesaj', models.TextField()),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('reducere_procentuala', models.IntegerField()),
                ('reducere_fixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genuri', models.ManyToManyField(to='aplicatie.gen')),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.gen')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.bluray')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_vizualizare'],
            },
        ),
    ]
