# Generated by Django 5.1.1 on 2025-01-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0004_promotie_vizualizare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vizualizare',
            name='gen',
        ),
        migrations.RemoveField(
            model_name='vizualizare',
            name='produs',
        ),
        migrations.RemoveField(
            model_name='vizualizare',
            name='user',
        ),
        migrations.DeleteModel(
            name='Promotie',
        ),
        migrations.DeleteModel(
            name='Vizualizare',
        ),
    ]
