# Generated by Django 5.1.1 on 2025-01-14 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0005_remove_vizualizare_gen_remove_vizualizare_produs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizarii', models.DateTimeField(auto_now_add=True)),
                ('bluray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.bluray')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_vizualizarii'],
            },
        ),
    ]
