# Generated by Django 5.1.1 on 2025-01-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0006_vizualizare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('reducere', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calitate_video', models.CharField(blank=True, max_length=10, null=True)),
                ('subtitrari', models.BooleanField(default=True)),
            ],
        ),
    ]
