# Generated by Django 5.1.1 on 2025-01-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0007_promotie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluray',
            name='imagine_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
