# Generated by Django 5.1.1 on 2025-01-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0009_remove_bluray_imagine_url_bluray_imagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='bluray',
            field=models.ManyToManyField(related_name='filme', to='aplicatie.bluray'),
        ),
    ]
